### ISSUE TITLE
Problem with land (one block size private land)

### ISSUE THREAD

**Issue by truaddict** [Sysca11/BedrockKit#4]
Hi, this bug is detected best with 1-block sized lands.

It is not 100% reproduced (for me it was like 50% - 2 of 4 cases)

Steps:
1) Buy 1 block sized land
2) Check land info while on this bought land.
3) land info will show "Land not found"
4) Make one step off this block (try all directions) - some of neighbour blocks will show land info.

Similar error was in linux BDL, but that bug was 100% reproducible and was caused by ServerPlayer-GetPos method returned Z+1 coordinate of player (in land query procedure).

**Comment by Sysca11** [comment]
It seems that mojang uses a very strange float -> int conversion rule.
-0.9 -> -1,-0.1 -> -1,0.1->0,0.9->0
I used this function to convert,and will fix it(maybe) on next push 
 int iround(float x) {
	int r = x;
	if (x < 0)
		r--;
	return r;
}

**Comment by Sysca11** [comment]
fixed in commit 6f16fda8d47bf42aec3d504136f5e8d84e1402c3
